# Generated by Django 3.1.2 on 2020-12-28 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='actvie',
            field=models.BooleanField(default=False),
        ),
    ]
