# Generated by Django 3.1.2 on 2020-11-25 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_auto_20201125_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='why_choose_us',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
