# Generated by Django 3.1.2 on 2020-11-30 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_auto_20201130_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertybook',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
