# Generated by Django 3.1.2 on 2020-11-30 19:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0009_auto_20201130_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertybook',
            name='name',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='user_book', to='auth.user'),
            preserve_default=False,
        ),
    ]
