# Generated by Django 3.1.2 on 2020-11-30 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20201130_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertybook',
            name='email',
        ),
    ]
