# Generated by Django 3.1.2 on 2020-12-02 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='place',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
