# Generated by Django 3.1.2 on 2020-12-02 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_auto_20201202_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='place',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='property_place', to='property.place'),
            preserve_default=False,
        ),
    ]
